### ISSUE TITLE
USB-C not working

### ISSUE THREAD

**Issue by jabsk** [lersy/Dell-7577-Hackintosh-macos-Opencore#12]
Hey, thanks a lot for the awesome build. I used your EFI folder to boot my Dell 7577 with i5 7300hq. Everything works as you have mentioned. Just a small help, I have tried but my USB-C port is not working. I have also changed my layout id as mentioned in one of the issue threads. Everything is enabled in my BIOS for TB3 with Security set to NO.

**Comment by lersy** [comment]
Hey mate. I am sorry for replying your message late. I have been quite busy lately. 

Have you managed to make it worked ? If not , please let me know. 

You can disable "USBPorts.kext" in config.plist and try again to see if it works or not. 

according to @ DeMikeyyy simply changing layout-id is enough. He knows better than me about this issue. I have no chance to try it, but next time I will fix it I hope.

**Comment by DeMikeyyy** [comment]
> Hey mate. I am sorry for replying your message late. I have been quite busy lately.
> 
> Have you managed to make it worked ? If not , please let me know.
> 
> You can disable "USBPorts.kext" in config.plist and try again to see if it works or not.
> 
> according to @ DeMikeyyy simply changing layout-id is enough. He knows better than me about this issue. I have no chance to try it, but next time I will fix it I hope.

I can't speak for the USB Type-C functionality as I don't use it. I only use it to output HDMI signal. Will you be releasing an update to 0.6.0? Cheers mate

**Comment by lersy** [comment]
@DeMikeyyy hey bro

I have been on OC 0.6.0 for a long time including beta phases and I can tell that no problem so far. Only thing kept me from releasing that I want to configure USBPorts.kext which include type+c ports as well. If you made it for yourself , can you share it to me? Mostly this causes the problem for other parties and even though I don't use it for myself , I want it to be preconfigured. 

thanks
