### ISSUE TITLE
HDMI system freeze

### ISSUE THREAD

**Issue by darksagas** [lersy/Dell-7577-Hackintosh-macos-Opencore#2]
First I wanted to thank you for such an amazing guide!!

I didn't have an USB 2.0 to install the system, but surprisingly I could install the OS using a thunderbolt pendrive, everything went as expected, except HDMI, I know you said you didn't have thunderbolt, but do you have any idea of what could be freezing then crashing the OS after trying to connect a monitor in my HDMI thunderbolt dongle?

**Comment by lersy** [comment]
Hey bro. Thanks for your message and sorry to reply it late. 

I have still clueless about HDMI. I have no information about thunderbolt mechanics. To my understanding it does not work on macOs because it is tied to NVIDIA and NVIDIA is closed. But I will dig into it when possible to provide sufficient information about this issue. Let me know if you have progress to make HDMI working.

**Comment by darksagas** [comment]
Yoooo I could solve it using https://github.com/wadimw/dell-7577-hackintosh HDMI configuration, second monitor is now working perfectly using thunderbolt adapter with no issues.

Cheers.

**Comment by DeMikeyyy** [comment]
> Yoooo I could solve it using https://github.com/wadimw/dell-7577-hackintosh HDMI configuration, second monitor is now working perfectly using thunderbolt adapter with no issues.
> 
> Cheers.

Yo man, so how did you fix the issue? I've been spending all day trying to get a screen working with the USB-C dongle. Did you switch back to CLOVER from wadimw or did you manage to fix it in opencore in the config.plist? Thanks!

**Comment by darksagas** [comment]
Just use the config.list used in the link above, focus only on the HDMI section. which is the PciRoot(0)/Pci(0x02,0) property.

Cheers. I'll try to share later my config.plist highlighting that specifically....

**Comment by DeMikeyyy** [comment]
> Just use the config.list used in the link above, focus only on the HDMI section. which is the PciRoot(0)/Pci(0x02,0) property.
> 
> Cheers. I'll try to share later my config.plist highlighting that specifically....

That's the first thing I did but sadly it didn't work or I just did/converted to HEX wrong/missed some properties (most properties are marked with # in wadimw's config in the HDMI part.

I'd be forever grateful if you could prove me with the info from that section! Cheers mate

**Comment by DeMikeyyy** [comment]
> Just use the config.list used in the link above, focus only on the HDMI section. which is the PciRoot(0)/Pci(0x02,0) property.
> 
> Cheers. I'll try to share later my config.plist highlighting that specifically....

Hey man, would you still be able to share the part of the HDMI section of the config.plist? Tha ks ☺️

**Comment by DeMikeyyy** [comment]
> Just use the config.list used in the link above, focus only on the HDMI section. which is the PciRoot(0)/Pci(0x02,0) property.
> 
> Cheers. I'll try to share later my config.plist highlighting that specifically....

Bro, are you planning on sharing the HDMI part? Otherwise I'll just go with Clover, I'm frustrated it doesn't work after trying everything lol. Cheers

**Comment by DeMikeyyy** [comment]
> Just use the config.list used in the link above, focus only on the HDMI section. which is the PciRoot(0)/Pci(0x02,0) property.
> 
> Cheers. I'll try to share later my config.plist highlighting that specifically....

I solved it using the 0001659 platform-id
