### ISSUE TITLE
dell 5577

### ISSUE THREAD

**Issue by priyanshuarora595** [lersy/Dell-7577-Hackintosh-macos-Opencore#21]
can you please provide efi folder for dell inspiron 5577 laptop . its an i5 7th gen with nvidia gtx 1050 , intel hd graphics 630. i have already tried https://github.com/Wmyaaa/Dell5577-hackintosh , but its not working , i am stuck on black screen . tried many fixes but nothing worked. 
thanks.

**Comment by lersy** [comment]
ok buddy maybe I can help you to run it but you need to provide more info about your situation. we can start with you upload the latest efi folder here and what you tried so far. don't you get any verbose log on screen? there should be some texts on it to say what is going on.

**Comment by uzairblaoch** [comment]
> can you please provide efi folder for dell inspiron 5577 laptop . its an i5 7th gen with nvidia gtx 1050 , intel hd graphics 630. i have already tried https://github.com/Wmyaaa/Dell5577-hackintosh , but its not working , i am stuck on black screen . tried many fixes but nothing worked.
> thanks.



You need to spoof skylake id to get it working. It won’t work on kabylake 
Just try 
Platform id : 0000001B19
Device id : 1619000000

With boot args : -disablegfxfirmware lilucup=8

**Comment by priyanshuarora595** [comment]
> ok buddy maybe I can help you to run it but you need to provide more info about your situation. we can start with you upload the latest efi folder here and what you tried so far. don't you get any verbose log on screen? there should be some texts on it to say what is going on.

i am uploading that efi which resulted in black screen.... [https://drive.google.com/drive/folders/1vW9QmyPMX0xyUJdpCO-VLEH6gF69Rebc?usp=sharing](url)

**Comment by priyanshuarora595** [comment]
> > can you please provide efi folder for dell inspiron 5577 laptop . its an i5 7th gen with nvidia gtx 1050 , intel hd graphics 630. i have already tried https://github.com/Wmyaaa/Dell5577-hackintosh , but its not working , i am stuck on black screen . tried many fixes but nothing worked.
> > thanks.
> 
> You need to spoof skylake id to get it working. It won’t work on kabylake
> Just try
> Platform id : 0000001B19
> Device id : 1619000000
> 
> With boot args : -disablegfxfirmware lilucup=8

okay... let me try this... thanks,,,

**Comment by priyanshuarora595** [comment]
> > can you please provide efi folder for dell inspiron 5577 laptop . its an i5 7th gen with nvidia gtx 1050 , intel hd graphics 630. i have already tried https://github.com/Wmyaaa/Dell5577-hackintosh , but its not working , i am stuck on black screen . tried many fixes but nothing worked.
> > thanks.
> 
> You need to spoof skylake id to get it working. It won’t work on kabylake
> Just try
> Platform id : 0000001B19
> Device id : 1619000000
> 
> With boot args : -disablegfxfirmware lilucup=8

Thank you so much man.... It worked.... Now i have 2gb graphics memory.... Thanks a lot man

**Comment by lersy** [comment]
Solved thanks to uzairblaoch so closing it for now

**Comment by uzairblaoch** [comment]
> > > can you please provide efi folder for dell inspiron 5577 laptop . its an i5 7th gen with nvidia gtx 1050 , intel hd graphics 630. i have already tried https://github.com/Wmyaaa/Dell5577-hackintosh , but its not working , i am stuck on black screen . tried many fixes but nothing worked.
> > > thanks.
> > 
> > 
> > You need to spoof skylake id to get it working. It won’t work on kabylake
> > Just try
> > Platform id : 0000001B19
> > Device id : [1619000000](tel:1619000000)
> > With boot args : -disablegfxfirmware lilucup=8
> 
> Thank you so much man.... It worked.... Now i have 2gb graphics memory.... Thanks a lot man

Your welcome bro :)

**Comment by priyanshuarora595** [comment]
Hii .... How did you managed to install big sur ????

**Comment by priyanshuarora595** [comment]
> > > > can you please provide efi folder for dell inspiron 5577 laptop . its an i5 7th gen with nvidia gtx 1050 , intel hd graphics 630. i have already tried https://github.com/Wmyaaa/Dell5577-hackintosh , but its not working , i am stuck on black screen . tried many fixes but nothing worked.
> > > > thanks.
> > > 
> > > 
> > > You need to spoof skylake id to get it working. It won’t work on kabylake
> > > Just try
> > > Platform id : 0000001B19
> > > Device id : 1619000000
> > > With boot args : -disablegfxfirmware lilucup=8
> > 
> > 
> > Thank you so much man.... It worked.... Now i have 2gb graphics memory.... Thanks a lot man
> 
> Your welcome bro :)

can you please tell how did you managed  to boot bigsur ? i am unable to even boot from installer usb . please help
