### ISSUE TITLE
Bigsur not working 

### ISSUE THREAD

**Issue by priyanshuarora595** [lersy/Dell-7577-Hackintosh-macos-Opencore#24]
I am using dell inspiron 15 5577 i5  Intel HD graphics 630

I am unable to boot macos bigsur. I always encounter black screen , although system in running (volume keys are working) . Please help me to get over with this. 
Thanks in advance 
@lersy

**Comment by lersy** [comment]
Sorry mate it has been a very long time since you posted this issue but I wonder did you manage to boot ?
