### ISSUE TITLE
USB not working in latest release

### ISSUE THREAD

**Issue by DeMikeyyy** [lersy/Dell-7577-Hackintosh-macos-Opencore#3]
Hey man!
I finally came around installing MacOS again. I tried your latest release but USB doesn't work anymore, I know you explained I have to fix them myself but I tried with Hackintool and USB Map but I really can't get them working.

It would be awesome if you could provide an EFI with working USB ports, I tried combining kexts/SSDT's from R1.1 with the latest release but I haven't got them working just yet.

Thanks again!

**Comment by lersy** [comment]
Hey mate.

I updated readme and uploaded an EFI folder with USB ports pre-configured again. check the latest release and let me know if it works. 

have you changed your display? how is it with comparing factory default?

**Comment by DeMikeyyy** [comment]
> Hey mate.
> 
> I updated readme and uploaded an EFI folder with USB ports pre-configured again. check the latest release and let me know if it works.
> 
> have you changed your display? how is it with comparing factory default?

Holy shit man, thanks again! That was fast!

Everything is working now, I didn't bother with your WiFi kext as I don't want to enable it through terminal manually everytime I boot. Doesn't matter as I have a WiFi dongle anyway.

I didn't buy the display yet, Corona hit the wallet hard lol.

The only thing I'm left thinking about if USB-C dongle works for using a monitor?

Also, if you don't want to spam that F12 button everytime you want to go into Windows, I installed refind, here's my minimal setup:

[https://www.imgur.com/OFsRT9n.jpg](url)


Cheers man! Thanks again

**Comment by lersy** [comment]
Mate, I barely hit that F12 button. Most of the time it boots directly into macOS because I surf on the internet and do nothing special. I boot to windows when I want to play Rocket League. I don't play it often once in a 3-4 days. 

But your minimal refind looks classy 👍🏼
