### ISSUE TITLE
DELL 7567

### ISSUE THREAD

**Issue by th146o** [lersy/Dell-7577-Hackintosh-macos-Opencore#4]
Hello.
I'm trying to install macOS CatalinaI 10.15.4 on a DELL 7567 with the specifications below, but freezes. Look image.

Can you help me?

Intel(R) Core(TM) i7-7700HQ CPU 2.80GHz
Intel HD Graphics 630
GTX 1050 TI 4GB
Qualcomm QCA61x4A 802.11ac Wireless Adapter
Qualcomm QCA61x4A Bluetooth
Intel(R) 100 Series/C230 Chipset Family SATA AHCI Controller

Thank you.

![error](https://user-images.githubusercontent.com/24367807/80544246-9fe9b680-897e-11ea-9296-4a6aecc73d22.jpeg)

**Comment by lersy** [comment]
Hey mate.
I have not seen these lines before and when I checked the resources there is no sufficient explanation. Which bios version is your laptop on? Before installing macOS I recommend you to update your bios to latest. 

Do you use my efi folder ? is it latest one? Have you changed anything on config.plist? I will dig into this more.
