### ISSUE TITLE
Pls help 

### ISSUE THREAD

**Issue by marcinkk** [lersy/Dell-7577-Hackintosh-macos-Opencore#8]
Hey, how do you set the keys to adjust the screen brightness on a laptop keyboard ?? Right now it's fn + f12 and fn + key pause. My bootloader is opencore. In my laptop acer v3-371, the shortcut from adjusting the screen brightness on the keyboard is the shortcut fn + left arrow key and fn + arrow right key.

**Comment by lersy** [comment]
hey mate.

information you provided is not sufficient. have you followed any guide? you need to provide some other values to make it work. 

my keyboard is attached to PS2K so if you investigate my ssdt it informs that part of DSDT. 

in my original dsdt, method for brightness key is called as "BRT6" so there is a rename patch in my config. 

https://osxlatitude.com/forums/topic/7890-how-to-fix-your-acpi-brightness-keys-using-smart-touchpad-driver/#comments

just read the guide here for a start and see what is your details about that. if you provide me further info, I will try to help you if I can.

have a good day.
