### ISSUE TITLE
Hdmi usb-c freeze solved

### ISSUE THREAD

**Issue by DeMikeyyy** [lersy/Dell-7577-Hackintosh-macos-Opencore#9]
Just use 0001659 instead of 00001B59

**Comment by lersy** [comment]
To make thing clear, only changing device id to 00001659 is enough? Have you used any other values from mentioned config.plist from wadimw? Can you share a screenshot of your corresponded area of config bro?

I am using 00001659 as you suggested now, there is no problem with internal screen but I do not have a chance to try a second screen as I said before.

Thanks for solution.

**Comment by DeMikeyyy** [comment]
> To make thing clear, only changing device id to 00001659 is enough? Have you used any other values from mentioned config.plist from wadimw? Can you share a screenshot of your corresponded area of config bro?
> 
> I am using 00001659 as you suggested now, there is no problem with internal screen but I do not have a chance to try a second screen as I said before.
> 
> Thanks for solution.

Hey bro, no thanks to me but thanks to you. I made a OC config myself and I got it booting but no usb/power management. I was thinking about starting from scratch as sharing EFI even on same hardware isn't recommended but I won't bother as some of your ssdt's aren't even mentioned in the OC laptop guide so I don't wanna lose months of time again troubleshooting instead of enjoying my laptop.

Here' some pictures for you, so yes, as you can see, simply changing the value to 00001659 does the trick and even hotplugging works!

https://imgur.com/4dvBIR7

https://imgur.com/r4l5LpD

**Comment by dbookuz** [comment]
guys, i tried changing my values too to this 00001659. HDMI-usb C is not working for me, even hdmi-hdmi doesn't work..

**Comment by lersy** [comment]
@dbookuz you should be careful about smbios parameters maybe it is because 14,3 comes with a dgpu and 14,1 comes only with igpu. 

@DeMikeyyy thanks for pictures and information bro. smbios trick is something making sense because 14,3 comes with a dgpu and 14,1 comes with a igpu. we are learning all together these useful tricks :)

**Comment by dbookuz** [comment]
so should i change my smbios to 14,1?

**Comment by lersy** [comment]
well bro I am clueless right now actually. it is just a suggestion even though @DeMikeyyy said it works on both smbios. maybe you should wait for his support to make it work because he knows more than me about this subject. if you have working iMessage and FaceTime maybe waiting instead of changing smbios is more logical think to do.

**Comment by dbookuz** [comment]
@DeMikeyyy I changed my smbios to 14,1 and the tb3 worked but the bluetooth and usb mouse doesn't work.. did u do other things other than changing smbios?

**Comment by lersy** [comment]
It is because USBPorts.kext You should change it is info.plist there are sections which says 14,3 you should change them to 14,1 to make usb ports work

**Comment by dbookuz** [comment]
@lersy do u have a discord sir or something, i don't want to spam @DeMikeyyy 's issue topic.. usb and bluetooth back to working again but the sounds when i disconnect the BT doesn't work and the sounds when connected to the thunderbolt, it doesn't play the sound on the 2nd monitor

**Comment by DeMikeyyy** [comment]
> @lersy do u have a discord sir or something, i don't want to spam @DeMikeyyy 's issue topic.. usb and bluetooth back to working again but the sounds when i disconnect the BT doesn't work and the sounds when connected to the thunderbolt, it doesn't play the sound on the 2nd monitor
> 
> edit: nvm, sound is working fine now.. only the sounds the second monitor doesn't work or maybe i didn't configure something

Hey bro, I think it's normal that sound doesn't work. I will check it out. Any other problems?

**Comment by BenediktBlana** [comment]
Hi guys, i5-7300HQ & GTX1060 usb-c->hdmi dongle is working (hotpluggable), using MacBook14,1 and 00001659 (Big Sur).
